# Generated by Django 2.2 on 2019-04-22 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('knowledgePointId', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='知识点编号')),
                ('knowledgePoint', models.CharField(max_length=15, verbose_name='知识点')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '5. 知识点',
                'db_table': 'knowledge_point',
            },
        ),
        migrations.CreateModel(
            name='QuizType',
            fields=[
                ('quizTypeId', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='试题分类编号')),
                ('quizTypeName', models.CharField(max_length=10, verbose_name='试题分类')),
            ],
            options={
                'verbose_name': '试题分类',
                'verbose_name_plural': '4. 试题分类',
                'db_table': 'quiz_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=12, verbose_name='用户名')),
                ('userPasswd', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '3. 用户信息',
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='QuizBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizId', models.CharField(max_length=20)),
                ('quizPointNum', models.CharField(choices=[('only', '单一'), ('many', '综合')], max_length=4, verbose_name='知识点数')),
                ('quizText', models.TextField(max_length=1000, verbose_name='试题文本')),
                ('quizFullScore', models.IntegerField(verbose_name='满分')),
                ('quizFilename', models.FileField(upload_to='%Y/%m/%d', verbose_name='文件名')),
                ('quizDifficulty', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='难度系数')),
                ('quizCreateTime', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('quizModifyTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('quizInputer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='录题人')),
                ('quizKnowledgePoint', models.ManyToManyField(to='backend.KnowledgePoint', verbose_name='知识点')),
                ('quizType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.QuizType', verbose_name='试题分类')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '1. 题库',
                'db_table': 'quiz_bank',
            },
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='quizType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.QuizType', verbose_name='试题分类'),
        ),
        migrations.CreateModel(
            name='ExerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultInfo', models.TextField(max_length=1000, verbose_name='批阅反馈')),
                ('quizScore', models.IntegerField(verbose_name='得分')),
                ('uploadFilename', models.CharField(max_length=20, verbose_name='文件名')),
                ('uploadStatus', models.BooleanField(verbose_name='是否已上传')),
                ('correctStatus', models.BooleanField(verbose_name='是否已批阅')),
                ('downloadTime', models.DateTimeField(verbose_name='下载时间')),
                ('uploadTime', models.DateTimeField(verbose_name='上传时间')),
                ('correctTime', models.DateTimeField(verbose_name='批阅时间')),
                ('correctFlag', models.BooleanField(verbose_name='可否批阅')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.QuizBank', verbose_name='试题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '练习记录',
                'verbose_name_plural': '2. 练习记录',
                'db_table': 'exer_record',
            },
        ),
    ]
