# Generated by Django 2.2 on 2019-04-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTopic', models.CharField(max_length=10, verbose_name='帖子主题')),
                ('postTitle', models.CharField(max_length=30, verbose_name='帖子标题')),
                ('postContent', models.CharField(max_length=1000, verbose_name='帖子内容')),
                ('postCreateTime', models.DateTimeField(auto_now_add=True, verbose_name='发帖时间')),
                ('postModifyTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('postPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User', verbose_name='发贴人')),
            ],
        ),
        migrations.CreateModel(
            name='PostReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyContent', models.CharField(max_length=1000, verbose_name='回复内容')),
                ('replyTime', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('postTopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.PostTopic', verbose_name='帖子主题')),
                ('replyPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User', verbose_name='回复人')),
            ],
        ),
    ]
