# Generated by Django 2.2 on 2019-04-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_postreply_posttopic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTopic',
            new_name='Post',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '讨论帖子', 'verbose_name_plural': '6. 讨论帖子'},
        ),
        migrations.AlterModelOptions(
            name='postreply',
            options={'verbose_name': '帖子回复', 'verbose_name_plural': '7. 帖子回复'},
        ),
        migrations.RenameField(
            model_name='postreply',
            old_name='postTopic',
            new_name='post',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
        migrations.AlterModelTable(
            name='postreply',
            table='post_reply',
        ),
    ]
