# Generated by Django 2.2 on 2019-04-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190423_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postContent',
            field=models.TextField(max_length=1000, verbose_name='帖子内容'),
        ),
        migrations.AlterField(
            model_name='postreply',
            name='replyContent',
            field=models.TextField(max_length=1000, verbose_name='回复内容'),
        ),
    ]
