# Generated by Django 2.2 on 2019-04-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190423_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postTopic',
            field=models.CharField(choices=[('word', 'word'), ('excel', 'excel'), ('ppt', 'ppt'), ('meta', 'meta'), ('exam', '等级考试'), ('work', '办公技巧')], max_length=10, verbose_name='帖子主题'),
        ),
    ]
